### PR TITLE
Dockerize app

### PR DESCRIPTION
**Pull request by FilomenoSanchez**
This `Dockerfile` can be used to dockerize the app. It also takes care of port mapping so that the container's port 3000 corresponds with the host's port 3000. At the moment it doesn't work as it crashes during compilation due to the `cannot find Python.h` error mentioned this morning so I couldn't fully test it but I see no reason why it wouldn't work once that is fixed as I have used this approach before.

### CODE REVIEW

**Comment by FilomenoSanchez** [comment]
Actually now it is crashing at a different point during compilation: 

```[ 42%] Building CXX object ccp4srs/CMakeFiles/ccp4srs.dir/__/checkout/ccp4srs/ccp4srs/ccp4srs_container.cpp.o
[ 42%] Building CXX object ccp4srs/CMakeFiles/ccp4srs.dir/__/checkout/ccp4srs/ccp4srs/memio_.cpp.o
/opt/ccp4_wasm/checkout/ccp4srs/ccp4srs/memio_.cpp:40:10: fatal error: 'zlib.h' file not found
#include <zlib.h>
         ^~~~~~~~
1 error generated.
em++: error: '/opt/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fignore-exceptions -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -DEMSCRIPTEN -I/opt/emsdk/upstream/emscripten/cache/sysroot/include/SDL --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -I/opt/ccp4_wasm/ccp4srs/. -I/opt/ccp4_wasm -I/opt/ccp4_wasm/ccp4srs -I/opt/ccp4_wasm/ccp4srs/.. -I/opt/ccp4_wasm/ccp4srs/../checkout/mmdb2 -I/opt/ccp4_wasm/ccp4srs/../checkout/libccp/ccp4 -O2 -c /opt/ccp4_wasm/checkout/ccp4srs/ccp4srs/memio_.cpp -o CMakeFiles/ccp4srs.dir/__/checkout/ccp4srs/ccp4srs/memio_.cpp.o' failed (returned 1)
make[2]: *** [ccp4srs/CMakeFiles/ccp4srs.dir/build.make:246: ccp4srs/CMakeFiles/ccp4srs.dir/__/checkout/ccp4srs/ccp4srs/memio_.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1089: ccp4srs/CMakeFiles/ccp4srs.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
emmake: error: 'make' failed (returned 2)
The command '/bin/bash -c source /opt/emsdk/emsdk_env.sh && emmake make' returned a non-zero code: 1
```
Not sure if this is related to the docker image or something else?

**Comment by FilomenoSanchez** [comment]
After the last changes it is now able to find `zlib.h`, but now I am getting the `Python.h` error:
```
[ 72%] Building CXX object coot/CMakeFiles/coot.dir/__/checkout/coot-1.0/lbg/lbg.cc.o
/opt/ccp4_wasm/checkout/coot-1.0/lbg/lbg.cc:22:10: fatal error: 'Python.h' file not found
#include <Python.h> // this is here get round header warnings
         ^~~~~~~~~~
1 error generated.
em++: error: '/opt/emsdk/upstream/bin/clang++ -target wasm32-unknown-emscripten -fvisibility=default -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-cxx-exceptions -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr -D__EMSCRIPTEN_SHARED_MEMORY__=1 -DEMSCRIPTEN -I/opt/emsdk/upstream/emscripten/cache/sysroot/include/SDL --sysroot=/opt/emsdk/upstream/emscripten/cache/sysroot -Xclang -iwithsysroot/include/compat -DANALYSE_REFINEMENT_TIMING -DDATADIR="/opt/ccp4_wasm/coot/../checkout/coot-1.0/data" -DHAVE_BOOST -DHAVE_CXX_THREAD -DHAVE_GSL -DPACKAGE_VERSION="1.0" -DPKGDATADIR="/opt/ccp4_wasm/coot/../checkout/coot-1.0/pixmaps" -DVERSION="1.0" -I/opt/ccp4_wasm/coot/../checkout/coot-1.0 -I/opt/ccp4_wasm/coot/../checkout/coot-1.0/coords -I/opt/ccp4_wasm/coot/../checkout/coot-1.0/utils -I/opt/ccp4_wasm/coot/../checkout/coot-1.0/src -I/opt/ccp4_wasm/coot/../include -I/opt/ccp4_wasm/coot/../example -I/opt/ccp4_wasm/coot/../checkout/ssm -I/opt/ccp4_wasm/coot/../checkout/mmdb2 -I/opt/ccp4_wasm/coot/../checkout/clipper -I/opt/ccp4_wasm/coot/../checkout/fftw-2.1.5/fftw -I/opt/ccp4_wasm/coot/../checkout/fftw-2.1.5/rfftw -I/opt/ccp4_wasm/coot/../checkout/libccp4/ccp4 -I/opt/ccp4_wasm/coot/../boost -O2 -pthread -DHAVE_BOOST -DNODERAWFS -DFFTW_ENABLE_FLOAT -std=gnu++11 -fexceptions -pthread -DHAVE_BOOST -DNODERAWFS -DFFTW_ENABLE_FLOAT -c -matomics -mbulk-memory /opt/ccp4_wasm/checkout/coot-1.0/lbg/lbg.cc -o CMakeFiles/coot.dir/__/checkout/coot-1.0/lbg/lbg.cc.o' failed (returned 1)
make[2]: *** [coot/CMakeFiles/coot.dir/build.make:2598: coot/CMakeFiles/coot.dir/__/checkout/coot-1.0/lbg/lbg.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1524: coot/CMakeFiles/coot.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
emmake: error: 'make' failed (returned 2)
The command '/bin/bash -c source /opt/emsdk/emsdk_env.sh && echo "" > silly.c && emcc silly.c -s USE_ZLIB=1 -s USE_LIBPNG=1 && rm -f silly.c && emmake make' returned a non-zero code: 1
```

**Comment by martinemnoble1** [comment]
Hi Stuart,

Paul has held his hands up to having missed out adding a file to the api folder causing bombed compiles:

_ZN21molecules_container_t23copy_fragment_using_cidEiRKNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE (referenced by top-level compiled C/C++ code)

Have you got a fix for that in hand, or do we need to bug Paul ?

Cheers,

Martin

**Comment by stuartjamesmcnicholas** [comment]
I'll let you know in a few minutes. I'm in the middle of a build.

**Comment by stuartjamesmcnicholas** [comment]
The build problem should now be fixed.

**Comment by FilomenoSanchez** [comment]
I will try to build a new image and see if it works

**Comment by FilomenoSanchez** [comment]
Now `emmake make` runs fine but when I run `emmake make install` I'm seeing this: 

```
[100%] Built target prosmart_common
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:44 (file):
  file INSTALL cannot find
  "/opt/ccp4_wasm/react-app/node_modules/pako/dist/pako.js": No such file or
  directory.


make: *** [Makefile:74: install] Error 1
emmake: error: 'make install' failed (returned 2)
The command '/bin/bash -c source /opt/emsdk/emsdk_env.sh && echo "" > silly.c && emcc silly.c -s USE_ZLIB=1 -s USE_LIBPNG=1 && rm -f silly.c && emmake make install' returned a non-zero code: 1

**Comment by martinemnoble1** [comment]
Looks like you need to “npm install” in react-app ?

**Comment by FilomenoSanchez** [comment]
@stuartjamesmcnicholas I think this is OK to merge now, the image builds fine and the port mapping seems to be working.

**Pull request merged**
